### ISSUE TITLE
Canvas flicker on resize

### ISSUE THREAD

**Issue by ianharrigan** [Kode/KodeGarden#12]
With latest KG, there is a small flicker when you resize the panels. Seems this is because when canvas is resized it clears itself. Apparent solution is to render as soon as the canvas is resized. Not sure if KG client can do that? Or it has to be deeper in Kha - either way. Not a biggie.

Ian

**Comment by RobDangerous** [comment]
I spent the evening being confused about OpenGL's coordinate systems but now it's fixed and my brain is back in the right coordinate system. Actual problem was that it flickered when the worker thread didn't have a new frame ready in time and resizing panels provoked that. Main thread now renders into a texture and keeps that around until a new frame arrives (we can also use that for the screenshot function you talked about).

**Comment by ianharrigan** [comment]
Oh, nice. Very cool. 

And yeah, so much smoother! http://kodegarden.org/#e40438bba01b508d9f4c80a8f49c17ef1bb2c03e
